-- Idempotent schema, run on every start. It creates missing tables only and never
-- drops, rewrites, or reseeds existing data.

CREATE TABLE IF NOT EXISTS author (
    id   BIGINT      PRIMARY KEY,
    name VARCHAR(80) NOT NULL
);

-- Seed posts use fixed IDs below 1000 (see seed/demo-data.json). Posts created through
-- the API get generated IDs starting at 1000, so they never collide with seed IDs, and
-- a reset needs no identity restart (which would not be transactional in H2).
--
-- Column sizes allow for characters outside the Basic Multilingual Plane (two UTF-16
-- units each). The 120/5,000 character limits are enforced by the application.
CREATE TABLE IF NOT EXISTS post (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1000) PRIMARY KEY,
    author_id    BIGINT                      NOT NULL REFERENCES author (id),
    title        VARCHAR(240)                NOT NULL,
    body         VARCHAR(10000)              NOT NULL,
    published_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at   TIMESTAMP(6) WITH TIME ZONE
);

CREATE INDEX IF NOT EXISTS post_feed_order ON post (published_at DESC, id DESC);
